### ISSUE TITLE
More FoF2

### ISSUE THREAD

**Issue by Toni-Thersthol** [emics/ham_radio_propagation#12]
Hi,
What about adding all info per station from https://prop.kc2g.com/stations/? Then can you chose the most close station to your QTH.
Regards Toni 
SA6EAL

**Comment by emics** [comment]
Hi Toni,
What kind of information do you think is significant. 
During setup the list of stations is ordered by distance from latitude and longitude configured in your HA.

**Comment by Toni-Thersthol** [comment]
Hi Emiliano,

 

From a NVIS perspective, that I only use, FoF2 and FoE. Can you add those as sensors to every stations? 

 

I would also be nice to embed the complete chart. I tried to do this, but I couldn’t use the link. I am not that skilled in HA yet. 😊



 

 

I think other HAMS with a YAGI antenna can be interested of the below. 

 

 



 

73 SA6EAL

Toni

Från: Emiliano ***@***.***> 
Skickat: den 7 maj 2023 19:58
Till: emics/ham_radio_propagation ***@***.***>
Kopia: Toni-Thersthol ***@***.***>; Author ***@***.***>
Ämne: Re: [emics/ham_radio_propagation] More FoF2 (Issue #12)

 

Hi Toni,
What kind of information do you think is significant.
During setup the list of stations is ordered by distance from latitude and longitude configured in your HA.

**Comment by Toni-Thersthol** [comment]
I forgot. (Wish list increase. 😊)

 

Last updated in UTC. And if possible, a timer and/or that you can double-click to update. 

73

 

 

Hi Emiliano,

 

From a NVIS perspective, that I only use, FoF2 and FoE. Can you add those as sensors to every stations? 

 

I would also be nice to embed the complete chart. I tried to do this, but I couldn’t use the link. I am not that skilled in HA yet. 😊



 

 

I think other HAMS with a YAGI antenna can be interested of the below. 

 

 



 

73 SA6EAL

Toni

Från: Emiliano ***@***.***> 
Skickat: den 7 maj 2023 19:58
Till: emics/ham_radio_propagation ***@***.***>
Kopia: Toni-Thersthol ***@***.***>; Author ***@***.***>
Ämne: Re: [emics/ham_radio_propagation] More FoF2 (Issue #12)

 

Hi Toni,
What kind of information do you think is significant.
During setup the list of stations is ordered by distance from latitude and longitude configured in your HA.

**Comment by Toni-Thersthol** [comment]
Hi,

Realized that the below is a picture, I solved that. But It would be interesting to have FoF2 and FoE as sensors. Then can you use those in an automation.

 

73 Toni

 

 

 

 

I forgot. (Wish list increase. 😊)

 

Last updated in UTC. And if possible, a timer and/or that you can double-click to update. 

73

 

 

Hi Emiliano,

 

From a NVIS perspective, that I only use, FoF2 and FoE. Can you add those as sensors to every stations? 

 

I would also be nice to embed the complete chart. I tried to do this, but I couldn’t use the link. I am not that skilled in HA yet. 😊



 

 

I think other HAMS with a YAGI antenna can be interested of the below. 

 

 



 

73 SA6EAL

Toni

Från: Emiliano ***@***.***> 
Skickat: den 7 maj 2023 19:58
Till: emics/ham_radio_propagation ***@***.***>
Kopia: Toni-Thersthol ***@***.***>; Author ***@***.***>
Ämne: Re: [emics/ham_radio_propagation] More FoF2 (Issue #12)

 

Hi Toni,
What kind of information do you think is significant.
During setup the list of stations is ordered by distance from latitude and longitude configured in your HA.

**Comment by emics** [comment]
ok i still working for this new infos.

tnx

**Comment by emics** [comment]
Resolved with [v1.1.4 release](https://github.com/emics/ham_radio_propagation/releases/tag/v1.1.4)
