### ISSUE TITLE
Can you add a sensor that detects Solar Flares?

### ISSUE THREAD

**Issue by CT2HUU** [emics/ham_radio_propagation#14]
I'm trying to find a way to create a sensor that detects Solar Flares. As an Ham Radio operator I will take advantage on that.
I'm not getting much info for HA, but there is a project that is close ([https://community.home-assistant.io/.../solar-flux.../434299](https://community.home-assistant.io/t/solar-flux-sensor-to-detect-solar-flares/434299?fbclid=IwAR1FnLRx4HGWv-hNTv-KliCxH15-7vj48vceO_AV7nsn2YprZQEyIR_Z8og)) but not relating the NOAA data into a sensor that results in a sensor that says "A Flare just happened! It's a C9 flare".
Can you help?

**Comment by emics** [comment]
Hi CT2HUU in the next week i'll try to integrate this sensor.
thank you for your suggestion.

**Comment by emics** [comment]
Resolved with [Release v1.1.5](https://github.com/emics/ham_radio_propagation/releases/tag/v1.1.5)
