### ISSUE TITLE
MUF from Los Roquetes stopped updating

### ISSUE THREAD

**Issue by CT2HUU** [emics/ham_radio_propagation#19]
Hi
Everything was working fine, but on the 24th of may MUF from Los Roquetes Spain stopped updating. Just checked it on source and it is 29.617MHz and my HA says 14.78Mhz  since 24 of may. I have other friends HA having the same issue.
Looking at source site, looks like it received an update https://prop.kc2g.com/stations/
Can you help?

**Comment by emics** [comment]
checked and update correctly.
thanks for your issue
73
