### ISSUE TITLE
Valid units for the sensors

### ISSUE THREAD

**Issue by dragonjon** [emics/ham_radio_propagation#2]
Hi @emics , this is in the log. Thank for this work.

Entity sensor.ham_radio_propagation_solar_wind (<class 'custom_components.ham_radio_propagation.sensor.HamRadioSensor'>) is using native unit of measurement 'km/s' which is not a valid unit for the device class ('wind_speed') it is using; expected one of ['mph', 'kn', 'km/h', 'ft/s', 'm/s']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.ham_radio_propagation_solar_sig_noise_lvl (<class 'custom_components.ham_radio_propagation.sensor.HamRadioSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('signal_strength') it is using; expected one of ['dBm', 'dB']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.ham_radio_propagation_solar_geomag_field has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: UNSETTLD (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Thanks in advanced
Jon
EA7KDW - AJ6TP
73

**Comment by emics** [comment]
hi @dragonjon wich HA version did you have?
tnx
