### ISSUE TITLE
Not really an issue, but a suggestion

### ISSUE THREAD

**Issue by CT2HUU** [emics/ham_radio_propagation#20]
Hi again!
Would it be possible to add an entity with the Confidence value of the selected Ionosonde?
Have a look on https://twitter.com/HB9VQQ/status/1667829304384802816?t=D7orJRQF3Iq0aOR-9PoSMw&s=08 (not me) to see a few ideas. Or in https://www.ursi.org/files/CommissionWebsites/INAG/web-73/confidence_score.pdf
Also would be nice to have a way to select how often I would like the MUF sensor to be updated, every 5 min, 10min, etc...
Great work you have done, 73.

**Comment by emics** [comment]
hello, the **confidence parameter** for Ionosonde is very important, unfortunately I get the data from this [API](https://prop.kc2g.com/api/stations.json) and I don't know which of these values it could be, I think it's the "cs": 80.0. Can you help me?
`{
		"md": "2.750",
		"mufd": 20.49,
		"fof2": 7.45,
		"fbes": null,
		"foes": null,
		"id": 13665684,
		"hmf1": 197.936,
		"station": {
			"name": "Poker Flat, AK, USA",
			"code": "PF765",
			"id": 114,
			"longitude": "212.55",
			"latitude": "65.13"
		},
		"scalef2": 61.332,
		"foe": null,
		"yf2": 74.712,
		"cs": 80.0,
		"hme": 110.0,
		"he": null,
		"yf1": 76.908,
		"time": "2023-05-20T00:30:05",
		"tec": null,
		"fof1": 4.825,
		"hmf2": 307.369,
		"source": "giro",
		"hf2": 385.0
	},
`

As for the update time, it's a configuration that I wanted to include in the next releases, unfortunately I'm very busy with work this month, but I'll be able to develop it soon.
Thank you very much

**Comment by CT2HUU** [comment]
Yes it is. As far as I can see, it is.
But it's easy to find if it is or not;
1- go to https://prop.kc2g.com/stations/
2- pickup a few ionosondes you know or not and check de confidence column
3- try to extract from api the CS value from the same ionosondes that you picked on step 2, if the values match, you have BINGO!
This would be my steps if I had skills to extract values from an api... 
Hope it work. 
Thanks for reply

**Comment by emics** [comment]
Hi I've add new release only in beta for test nee feature:
Added Confidence sensor in Ionosonde Integration

**Comment by CT2HUU** [comment]
> Hi I've add new release only in beta for test new feature: Added Confidence sensor in Ionosonde Integration

Humm... Another thing to learn, "how to enable beta versions from a certain HACS Integration... Will check it out tomorrow.
Tks, 73

**Comment by emics** [comment]
Hi,  in HACS you select **Integrations** and **Ham Radio Propagation**.
In this page you click the three dots at top right corner, the third item is something like "_Download again_" (sorry but i have italian translation) .
In the popup you can enable beta releases.

73'

**Comment by CT2HUU** [comment]
@emics I already installed it, but I'm overloaded of work and, as at the first look, it was not working as expected I need to calm down on work and them I will have a look deeper on this issue around 26 or 27 of july.
Sorry...

**Comment by CT2HUU** [comment]
Hi @emics , sorry about the late answer.
The ionosonde that is closer to my QTH is Spain - Roquetes.
If I compare the values of the Confidence that I obtain on my HA with you integration with the values that I get on https://prop.kc2g.com/stations/ they don't match.
Not really sure in who I can "trust more"... Your source is the same, right? If it is, why is it showing different values?

Another suggestion is that we can choose the update interval when we setup the integration, like every 5min, 10min, 30min.
73

**Comment by emics** [comment]
In the next release i want add a parameter for update interval, but now i don't have time.
About the Confidence value there are different update time:

- kc2g.com update data from 10 to 50 minutes
- my web service update the data from kc2g.com site every 30 minutes 
- the Ham Radio Propagation integration update every hour

this is the true.
