### ISSUE TITLE
Austin, TX no longer updating

### ISSUE THREAD

**Issue by techfixpros** [emics/ham_radio_propagation#26]
Austin, and many other stations are no longer updating.

**Comment by GlosVaper** [comment]
Yes, the UK has "dropped off the map" too e.g. Chilton, United Kingdom

**Comment by emics** [comment]
Hi @techfixpros you can go on the official page [kc2g.com](https://prop.kc2g.com/stations/),
search the station and verify yourself the TIME  column, Austin last update was 2024-04-17T19:05:05.
Unfortunately not all station are always active.

Thanx for your report
73 de IZ0IJD Emiliano

**Comment by techfixpros** [comment]
Thank you for the info. I did see they hadn't updated on the site in some time.
