### ISSUE TITLE
FoF2 seems to have disappeared since 29/5 04:03 UT

### ISSUE THREAD

**Issue by garethhowell** [emics/ham_radio_propagation#28]
I'm running V1.1.6 and connected to the default source as well as a local Echosonde station.

I've had this integration added for some time and I graph the sensor data in grafana. This morning I see that the FoF2 sensor is unavailable. Looking deeper I can see the data stream stopped on 29/5 at 04:03 UTC.

Any ideas why?

**Comment by emics** [comment]
Hi Gareth, last week we changed the component that collects data from websites in order to format it correctly in home assistant.
We noticed, following a user's report, that when some values ​​were not available we mistakenly entered zero as the value. This resulted in an error when drawing graphs in HA. You can see 
[this ISSUE](https://github.com/emics/ham_radio_propagation/issues/28) for detail.

tnx for your report!

**Comment by garethhowell** [comment]
Thanks for the update. I think my issue is slightly different,  it you’ll know better. 
it’s not that there are gaps in the reporting of FoF2; it’s that it is never reported. All other indices have the occasional gap, but FoF2 has gone completely. For me anyway.

**Comment by emics** [comment]
the FoF2 value of which station?

**Comment by garethhowell** [comment]
That from the site "Solar Data".

**Comment by emics** [comment]
Sorry for my misunderstand.
Integration get data from [hamqsl.com](https://www.hamqsl.com/) web site and you can see in the [XML page](https://www.hamqsl.com/solarxml.php), which is called by the integration at regular time intervals, the **fof2** value (at the end of page) is blank.

![screenshot](https://github.com/emics/ham_radio_propagation/assets/1004363/ccc9534a-2406-4d51-8b3e-a71811280db9)


I suggest you to add another  HAM Radio Propagation Integration in your Home Assistant, choice `MUF from ionosonde data` and select the stations near you getting most reliable value with data from another source [kc2g.com](https://prop.kc2g.com/stations/).

give me your feedback Gareth!
73

**Comment by garethhowell** [comment]
That's fine, Emiliano. I already had the Belgian echosonde. If it is that the feed no longer has foF2 - even though it is on the website - there's nothing you can do.
Thanks for responding. I'll close this now.
