### ISSUE TITLE
#BUG -Integration has lost access to the Chilton Ionosonde

### ISSUE THREAD

**Issue by L81ker** [emics/ham_radio_propagation#31]
The Chilton site and the ionosonde is still up and running, I was able to get todays data (1st Sept 2024) but the integration is no longer able to access it and I regularly get an error message about it.

I will check for log entries and add them here as comment as I find them.

![image](https://github.com/user-attachments/assets/cdb6a8f1-8387-4591-8998-1986f405bcf1)

![image](https://github.com/user-attachments/assets/ad4c75a5-a141-4aee-b18b-cbc457c28b41)

**Comment by emics** [comment]
Hi @L81ker thanks for your report.
The data are parsed from [kc2g.com](https://prop.kc2g.com/stations/) . 
If you go to the web site and search for "Chilton" you can see last data received is 22 August 

![screen](https://github.com/user-attachments/assets/f704dca7-7a33-4f69-9ad5-f9e5f71867ad)

Maybe the Chilton station is active but don't send data to kc2g.com, i can't do nothing.

**Comment by emics** [comment]
I noticed that there are 12 stations that have not transmitted data since August 22nd at 19:00, perhaps the site [kc2g.com](https://prop.kc2g.com/) is having problems.

**Comment by L81ker** [comment]
> Hi @L81ker thanks for your report. The data are parsed from [kc2g.com](https://prop.kc2g.com/stations/) . If you go to the web site and search for "Chilton" you can see last data received is 22 August
> 
> ![screen](https://private-user-images.githubusercontent.com/1004363/363479584-f704dca7-7a33-4f69-9ad5-f9e5f71867ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODgyMTUsIm5iZiI6MTcyNTE4NzkxNSwicGF0aCI6Ii8xMDA0MzYzLzM2MzQ3OTU4NC1mNzA0ZGNhNy03YTMzLTRmNjktOWFkNS1mOWU1ZjcxODY3YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMTA1MTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE3MmIyM2Y4ZjkxZjc5NjBlMjM5NzY4MzJmOWQ5OTg4ZmY4YWJlYjU5MThiZGRiMWNmNmViN2IwYTZmOTE4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Z-dMlXdWE6QioMd6I2xY8X10ywlBHAJOCX5qMNtFBc)
> 
> Maybe the Chilton station is active but don't send data to kc2g.com, i can't do nothing.

I looked him up on QRZ.com and dropped him an email about it. I see that his blog page was last updated in May. https://www.kc2g.com/ so he might be travelling or something. Nice presentation about his page here in YouTube as well https://youtu.be/Yn5-FdgssoY?si=1qCrF5ssMSsK7iQ1&t=61
