### ISSUE TITLE
ADD INTEGRATION HAM Radio Propagation

### ISSUE THREAD

**Issue by DL4DP** [emics/ham_radio_propagation#8]
Hello everyone,

I installed HAM Radio Propagation via HACS.

![Bild Fehler 4](https://user-images.githubusercontent.com/101423128/236142693-4b600f1f-71b7-43b3-8cfd-87282220f76f.png)

![Bild Fehler 2](https://user-images.githubusercontent.com/101423128/236140873-a499b972-939a-4a31-92bd-3f961bf53509.png)

I now wanted to add the integration

![Bild Fehler](https://user-images.githubusercontent.com/101423128/236140339-300b5925-7800-4260-a3f9-bb4fa19095f0.png)

Unfortunately, the integration is not offered to me for selection.

When I open the Botten from the side, the following message appears in the Home Assistant

![Bild Fehler 3](https://user-images.githubusercontent.com/101423128/236141946-fbb969a3-e3d6-4a62-a088-afb15e8fb66d.png)
 Übersetzter Text :-)

Mistake
This integration does not support UI configuration. If you followed this link from the Home Assistant website, make sure you're running the latest version of Home Assistant.

If I understand your instructions correctly, I'm not making a mistake.

Maybe you can help me?

Thanks says Dirk DL4DP

**Comment by emics** [comment]
Hi Dirk ,
did you have restart Home Assistant after HACS installation?
What Home Assistant version did you have?

**Comment by DL4DP** [comment]
hi emicd, since the new update it works.THX 73 de Dirk DL4DPAm 04.05.23, 11:40 schrieb Emiliano ***@***.***>:

   
  Hi Dirk , did you have restart Home Assistant after HACS installation? What Home Assistant version did you have?

**Comment by emics** [comment]
Hi Dirk. Thanks for reply. 
enjoy
